const QUESTION = {
    FETCH: 'QUESTION_FETCH',
    FETCH_ERROR: 'QUESTION_FETCH_ERROR',
    FETCH_SUCCESS: 'QUESTION_FETCH_SUCCESS',
    SUBMIT_SUCCESS: 'QUESTION_SUBMIT_SUCCESS',
    FETCH_SINGLE_SUCCESS: 'QUESTION_FETCH_SINGLE_SUCCESS'
}

const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
}

const SOLUTION = {
    FETCH: 'SOLUTION_FETCH',
    FETCH_ERROR: 'SOLUTION_FETCH_ERROR',
    FETCH_SUCCESS: 'SOLUTION_FETCH_SUCCESS',
    SUBMIT_SUCCESS: 'SOLUTION_SUBMIT_SUCCESS'
}

const COMMENT = {
    FETCH: 'COMMENT_FETCH',
    FETCH_ERROR: 'COMMENT_FETCH_ERROR',
    FETCH_SUCCESS: 'COMMENT_FETCH_SUCCESS',
    SUBMIT_SUCCESS: 'COMMENT_SUBMIT_SUCCESS'
}

export {QUESTION, ACCOUNT, SOLUTION, COMMENT};